# -*- coding: utf-8 -*-

"""
    rewardsciencesapilib.controllers.reward_categories

    This file was automatically generated by APIMATIC BETA v2.0 on 09/13/2016
"""

from .base_controller import *



class RewardCategories(BaseController):

    """A Controller to access Endpoints in the rewardsciencesapilib API."""

    def __init__(self, http_client = None, http_call_back = None):
        """Constructor which allows a different HTTP client for this controller."""
        BaseController.__init__(self, http_client, http_call_back)

    def list(self,
                limit = 25,
                offset = 0):
        """Does a GET request to /reward_categories.

        List all the available reward categories.

        Args:
            limit (int, optional): The number of reward categories you want to
                be retrieved.
            offset (int, optional): The number of reward categories you want
                to skip before starting the retrieval.

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # The base uri for api requests
        _query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        _query_builder += '/reward_categories'

        # Process optional query parameters
        _query_parameters = {
            'limit': limit,
            'offset': offset
        }
        
        # Validate and preprocess url
        _query_url = APIHelper.clean_url(_query_builder)

        # Prepare headers
        _headers = {
            'user-agent': 'APIMATIC 2.0',
            'Accept': Configuration.accept,
            'Content-Type': Configuration.content_type,
            'Authorization': 'Bearer ' + Configuration.o_auth_access_token
        }

        # Prepare the API call.
        _request = self.http_client.get(_query_url, headers=_headers, query_parameters=_query_parameters)

        # Invoke the on before request HttpCallBack if specified
        if self.http_call_back != None:
            self.http_call_back.on_before_request(_request)

        # Invoke the API call  to fetch the response.
        _response = self.http_client.execute_as_string(_request)

        # Wrap the request and the response in an HttpContext object
        _context = HttpContext(_request, _response)

        # Invoke the on after response HttpCallBack if specified
        if self.http_call_back != None:
            self.http_call_back.on_after_response(_context)

        # Global error handling using HTTP status codes.
        self.validate_response(_context)    

        # Return appropriate type
        return APIHelper.json_deserialize(_response.raw_body)


