# -*- coding: utf-8 -*-

"""
   rewardsciencesapilib.configuration

   This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/13/2016
"""

class Configuration(object):
    # The base Uri for API calls
    BASE_URI = 'https://api.rewardsciences.com'

    accept = 'application/vnd.rewardsciences.v1+json';

    content_type = 'application/json';

    # The OAuth 2.0 access token to be set before API calls
    # TODO: Replace the o_auth_access_token with an appropriate value
    o_auth_access_token = "TODO: Replace"


