# -*- coding: utf-8 -*-

"""
    rewardsciencesapilib.reward_sciences_api_client

    This file was automatically generated by APIMATIC BETA v2.0 on 09/13/2016
"""

from .http import *
from .models import *
from .exceptions import *
from .decorators import *
from .controllers import *

class RewardSciencesAPIClient(object):

    @lazy_property
    def rewards(self):
        return Rewards()

    @lazy_property
    def users(self):
        return Users()

    @lazy_property
    def reward_categories(self):
        return RewardCategories()

    @lazy_property
    def activities(self):
        return Activities()



